version: "3.3"

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - ./app/:/home/app/web/
      # - static_volume:/home/app/web/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - ./.env.prod
    environment:
      - NODE_ENV=production
    # depends_on:
    #   - db

  nginx:
    build: ./nginx
    volumes:
      - ./app:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

  # db:
  #   image: postgres
  #   volumes:
  #     - ./app:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=postgres
  #   ports:
  #     - "5432:5432"
